---
title: "Why R?"
author: ["Jasmine Hughes", "Michael McCarthy"]
---

```{r setup, include=FALSE}
source("setup/_common.R")
knitr::opts_chunk$set(echo = FALSE)
```

## What is R?

*  R is a programming language
*  R is **Open Source** and **free**!
*  It is a full-featured programming language, in particular a scripting language. 
   + This makes it similar in many ways to MATLAB and Python
*  It is designed by statisticians for statisticians 
*  R is being actively developed with ongoing updates/new releases
*  Available for Windows, Mac OS X, and Linux

### Why should I use R?

(Other than that PHC 506 requires it!)

* R is widely used (statisticians, scientists, social scientists) 
* R has tools for pharmacometrics! Examples: 
  + `nlmixr` nonlinear mixed effects modelling in R 
  + `PKPDsim` ODE solver/concentration time curve simulations
  + `mrgsolve` ODE solver/concentration time curve simulations 
  + `mapbayr` MAP Bayesian estimation of PK parameters
  + `vpc` visual predictive checks of NLMEM/NONMEM results
  + `PKNCA` pharmacokinetic non-compartmental analysis
  + And many, many more tools! Check out more here: https://cran.r-project.org/web/views/Pharmacokinetics.html
* Users add functionality via packages all the time
* R is free and available on all major platforms
  + works well with other collaboration tools like git
* R is very powerful, flexible, and easy to use
* R allows for reproducibility and automating tasks
* R can do essentially anything!
  + For a particularly creative use, check out this repo: <https://github.com/cutterkom/generativeart>
* Wide usage helps to improve quality and reduce bugs
* Wide usage means there's a lot of tools available online for help
* R is a great stepping stone to other languages!

### Why Should I Not Use R?

* Other software can be better than R at certain tasks 
* The *exact* task you need to do was already solved by someone else in some 
other language. 
* The task you need to do requires exceptional speed (R is not as fast
as some languages)
* R's packages are only as good as the person who wrote them; no
explicit quality control + Validation tools to vet package quality exist! Check
out: <https://github.com/pharmaR/riskmetric>

### What are my other options? Get me out of here!

* Python
* Matlab/Octave
* Julia (for pharmacometrics, see `pumas`)
* C/C++
* SAS
* Stata

### Why should I bother learning a coding language when AI tools can do it for me?

AI tools can be very helpful, but they are a complement to (not a replacement
for) your own ability to reason about a problem. It is error-prone, often
out-of-date, and typically missing important context. At the end of the day, you
will be responsible for the code you write, so will need to know how to read and
write code.

* Understand how to adapt, debug, tailor, and interpret the code genAI gives you
* Use the right language to communicate with others about software, and to
  interact with genAI tools about code
* Think about data and mathematical modeling in a way that works well with 
  software
* Reason abstractly, break a problem down into its components without losing
  sight of interconnectedness.
