---
title: "Additional Resources"
---

The lectures in this book are a starting point. The following books and
references will help you keep learning and mastering R well beyond what we cover
in class---they come highly recommended.

## Books

### [Hands-On Programming with R](https://rstudio-education.github.io/hopr/)

This book teaches you how to program in R with hands-on examples. It was written
for non-programmers as a friendly introduction to the language. You'll learn how
to load data, assemble and disassemble data objects, navigate R's environment
system, write your own functions, and use all of R's programming tools ---
solving practical data science problems along the way.

A great place to start is the
[Preface](https://rstudio-education.github.io/hopr/preface.html) and
[Chapter 1](https://rstudio-education.github.io/hopr/project-1-weighted-dice.html),
which pair well with Lecture 1.

### [R for Data Science](https://r4ds.hadley.nz)

This book teaches you how to do data science with R: how to get your data into
R, put it into the most useful structure, transform it, visualize it, and model
it. It covers the grammar of graphics, literate programming, and reproducible
research, along with best practices for wrangling, visualizing, and exploring
data.

## Cheat sheets

For quick, printable references on individual packages such as `dplyr` and
`ggplot2`, see Posit's cheat sheet collection at
<https://rstudio.github.io/cheatsheets/contributed-cheatsheets.html>. A condensed
summary of the functions used in this course is also in the
[R Cheat Sheet](R_cheatsheet.qmd) appendix.

## Getting help

R has a large, welcoming community. When you get stuck, searching
[Stack Overflow](https://stackoverflow.com/questions/tagged/r) or the relevant
package's GitHub issues will often turn up an answer---and R's built-in help
(`?function_name`) is always a good first stop.
